name: safe-regions
channels:
  - pytorch
  - defaults
  - conda-forge
  - fvcore
  - yaml
  - wandb
  - matplotlib
dependencies:
  - python=3.8.2
  - pytorch=1.8.1
  - torchvision=0.9.1
  - ray=1.2.0
  - tqdm=4.61.0
  - pip
