config:
    # resolution
    resolution: [32, 32]
    # model name
    model_name: "vgg16"
    # dataset name
    dataset_name: "cifar10"
    # train dataset
    train_dataset_path: "/media/andrijazz/datadrive/datasets/cifar10"
    # val dataset
    val_dataset_path: "/media/andrijazz/datadrive/datasets/cifar10"
    # train batch size per gpu
    train_batch_size: 64
    # number of epochs
    train_num_epochs: 100
    # restore from wandb or local
    train_restore_storage: ""
    # path to checkpoint from which to be restored
    train_restore_file: ""
    # learning rate
    learning_rate: 0.001
    # validation batch size
    val_batch_size: 64
    # log freq
    train_log_freq: 100
    # plot graphs to wandb
    plot_graphs_to_wandb_log_freq: 0
    # log video
    log_video: true
